### ISSUE TITLE
Manually entering a URL resets the selected language

### ISSUE THREAD

**Issue by danielp0505** [THM-ATLAS/vue-frontend#152]
Manually entering URLs sets the language to German.

**Comment by eznavy** [comment]
This should get fixed with #144.

**Comment by Resteklicken** [comment]
> This should get fixed with #144.

Good point, are you working on this?

**Comment by eznavy** [comment]
> > This should get fixed with #144.
> 
> Good point, are you working on this?
No, but I could. However, I am not sure whether to do use local- or sessionStorage, and whether I should do this today, as we said that Sunday would be the last day to actively work on the increment.

**Comment by Resteklicken** [comment]
Just wanted to avoid duplicate work, since I had _just_ assigned myself. I can do it if you're not too keen on it ;)
@hwgn executive decision needed: should we implement and fix this today?

**Comment by eznavy** [comment]
> Just wanted to avoid duplicate work, since I had _just_ assigned myself. I can do it if you're not too keen on it ;) @hwgn executive decision needed: should we implement and fix this today?

I am currently adding exemplary exercises as requested in Rocket Chat, so I won't be able to work on it anymore (today). :)

**Comment by hwgn** [comment]
> Just wanted to avoid duplicate work, since I had _just_ assigned myself. I can do it if you're not too keen on it ;) @hwgn executive decision needed: should we implement and fix this today?

I say go ahead, but if it's too much we'll just merge it next sprint, no problem
