### ISSUE TITLE
Pagination on course overview does not work

### ISSUE THREAD

**Issue by Resteklicken** [THM-ATLAS/vue-frontend#156]
The pagination on the course view either does not work (not interactable) or displays too many pages:  

![Screenshot from 2022-05-24 13-42-50](https://user-images.githubusercontent.com/44051775/170026980-2a340264-26d1-4186-a3f6-0ce73cc66506.png)

**Comment by hwgn** [comment]
it's currently disabled, but yeah we could consider cutoffs for the course list and display them, maybe 5 per page for now
