### ISSUE TITLE
Line breaks in exercise admin panel exercise preview don't consider word endings

### ISSUE THREAD

**Issue by hwgn** [THM-ATLAS/vue-frontend#160]
![image](https://user-images.githubusercontent.com/19843204/170042190-045dc1af-2ea1-4e1e-bed3-cf559bdb0358.png)
Text should instead break at word endings.

**Comment by eznavy** [comment]
If no good solution can be found, the text to display could be altered like this:

![image](https://user-images.githubusercontent.com/103522073/170288977-1d0b4d24-e317-48c2-8449-1fff1ba44ff9.png)

**Comment by hwgn** [comment]
Turns out this is a md-editor issue - css styling does not work. See [md-editor-v3#109](https://github.com/imzbf/md-editor-v3/issues/109#issue-1252520313)
