### ISSUE TITLE
Make Admin Panel Exercise View more mobile friendly

### ISSUE THREAD

**Issue by Resteklicken** [THM-ATLAS/vue-frontend#182]
Maybe we could make the table a bit wider on mobile devices:  

![Screenshot from 2022-05-29 16-23-08](https://user-images.githubusercontent.com/44051775/170874283-3cade498-9431-48a8-9342-6e3c398337a7.png)

_Originally posted by @Resteklicken in https://github.com/THM-ATLAS/vue-frontend/pull/177#pullrequestreview-988629397_

**Comment by eznavy** [comment]
This practically addresses the issue I wanted to work on with #169. :D

**Comment by Resteklicken** [comment]
> This practically addresses the issue I wanted to work on with #169. :D

Sorry you're right, couldn't really tell from the description of that issue :p
