### ISSUE TITLE
[Major] Notifications

### ISSUE THREAD

**Issue by hwgn** [THM-ATLAS/vue-frontend#196]
Progress:   

- [x] Notification Type
- [x] Notification Service 
- [x] Navbar displaying number of notifications 
- [x] Mobile navbar displays dot  
- [x] Regularly retreive new notifications from backend
- [x] Check for 'read' status of notifications 
- [x] Display notifications on Notifications Page
- [x] Mark notifications as read
- [x] Delete notifications
- [x] Display text notification content in popup on click and mark it read
- [x] Navigate to submissions etc. on click and mark notification as read

**Comment by Resteklicken** [comment]
Input welcome, otherwise I'm just going to wing it :zany_face:   
I'd do a dedicated site, since I find MOTD pop ups annoying.   
It could support marking things as read - either by storing the IDs of read news in localStorage, cookies, or the user account in the backend.

**Comment by hwgn** [comment]
Sounds good! Marking posts as read might be easiest to implement through notifications (which could be an issue we could start with now, too, at least frontend) which either way should be handled through backend

**Comment by Resteklicken** [comment]
Progress:   

- [x] Notification Type
- [x] Notification Service 
- [x] Navbar displaying number of notifications 
- [x] Mobile navbar displays dot  
- [ ] Regularly retreive new notifications from backend
- [ ] Check for 'read' status of notifications 
- [ ] Display notifications on Notifications Page
- [ ] Mark notifications as read
- [ ] Delete notifications
- [ ] Option to send notification to all users via admin panel
