### ISSUE TITLE
[Bug] Skip to Content Button always visible

### ISSUE THREAD

**Issue by Resteklicken** [THM-ATLAS/vue-frontend#208]
The "Skip to content" button is always visible as a white line at the top of the screen:  
![Screenshot from 2022-06-09 11-11-04](https://user-images.githubusercontent.com/44051775/172811699-a0f74edc-24dc-4610-ba35-b71a0f8ac38a.png)
   
I vaguely remember we talked about how we couldn't find a fix for this, but we should still track it.

**Comment by eznavy** [comment]
On which branch does this issue occur? I tested it on development with multiple browsers and I can't see the white line.

**Comment by Resteklicken** [comment]
This is in Google Chrome on the Development branch on my 1920x1080 monitor and my 1920x1080 laptop screen.   
You can even see it with the light theme if you look really closely:   
![Screenshot from 2022-06-10 19-39-32](https://user-images.githubusercontent.com/44051775/173121561-09005bd5-a26d-4d40-9cb8-edb8fdbf672e.png)
