### ISSUE TITLE
[Major] Change all pages hinting at functionality for users who are not logged in.

### ISSUE THREAD

**Issue by danielp0505** [THM-ATLAS/vue-frontend#209]
Due to back-end changes users who aren't logged in can't access most of the site, the site does not hint at this at all and the text on the help page currently contradicts this, stating that users who are not logged in may browse the site.

- [ ] Hide buttons that redirect to pages inaccessible to users who are not logged in (e.g. links to module search page on the landing page and in the header) unless they are logged in.
- [ ] Change descriptions on the help page to accurately state how the site currently works.
- [ ] Adjust landing page: Tell users to create a guest account if they want to use the website

**Comment by Resteklicken** [comment]
I can try tomorrow. Love these last minute major updates.

**Comment by hwgn** [comment]
> I can try tomorrow. Love these last minute major updates.

That's how we do it here 😎

**Comment by hwgn** [comment]
Cannot be done until the backend allows *some* api requests without auth, right now all requests require auth
