### ISSUE TITLE
[Bug] Giving oneself the tutor-role creates errors

### ISSUE THREAD

**Issue by eznavy** [THM-ATLAS/vue-frontend#216]
I played around with my roles in the admin panel for testing purposes and noticed errors in the console when trying to give myself the role tutor. (works with every other role)

![image](https://user-images.githubusercontent.com/103522073/173204707-4e55f19a-25ac-40b6-b863-8a29252c277e.png)

**Comment by hwgn** [comment]
![image](https://user-images.githubusercontent.com/19843204/173576444-675d6722-daf8-4507-9238-03f473827fa7.png)
This seems to be intentional. It seems like we need to manually disallow assigning tutor globally
