### ISSUE TITLE
Fix skip to content on Firefox

### ISSUE THREAD

**Issue by hwgn** [THM-ATLAS/vue-frontend#24]
Currently, the skip to content button appears and appends `#content` to the end of the URL, but this doesn't move the tab position to content.

**Comment by eznavy** [comment]
Ich hab eben Firefox installiert, bei mir funktioniert das Navigieren in den Content so wie es soll. Aber ich hab ja gesehen, dass es bei dir nicht ging... Ist dein Firefox up-to-date?

**Comment by hwgn** [comment]
Seems to be fixed with Firefox Version 100.0
