### ISSUE TITLE
[Bug] Strange behavior inside md-editor with enumerations

### ISSUE THREAD

**Issue by hwgn** [THM-ATLAS/vue-frontend#254]
Copy this text into a md-editor frame:
```
1. Schreiben Sie einen Ausdruck/eine Methode, die die geraden Zahlen in den Folgen aufaddiert
2. Schreiben Sie einen Ausdruck/eine Methode, die alle Zahlen in den Folgen quadriert
```

and press enter anywhere in the text. On the official docs, this results in a new enumeration point being created and the text behind the cursor to shift down. In our version it seems to skip ahead a few characters but create no new newlines or points.

https://imzbf.github.io/md-editor-v3/index vs http://localhost:3000/2/e/46/edit

**Comment by eznavy** [comment]
This issue must have occurred very recently, as it works fine on http://brueckenkurs-programmieren.thm.de.
