### ISSUE TITLE
[Minor] Gendering

### ISSUE THREAD

**Issue by eznavy** [THM-ATLAS/vue-frontend#266]

**Comment by hwgn** [comment]
Where? :D

**Comment by eznavy** [comment]
> Where? :D

The whole help page, profile page (roles, unless they won't be translated to german soon), admin panel ("Benutzer verwalten"), are some I just found.

**Comment by shinymew2** [comment]
I changed some text but I'm not sure if I got all of it and if I used the right way to gender (I used `:`, but maybe another type of gendering is more pleasing to read?)
You can checkout [this branch](https://github.com/THM-ATLAS/vue-frontend/tree/266-minor-gendering) for current progress.

**Comment by hwgn** [comment]
Looks good to me, you could create a PR for that if you like. I don't think we can get them perfect, but using `:` seems like a good option, since we're doing that everywhere else already too :)
