### ISSUE TITLE
[Major] Proper login lifecycle management

### ISSUE THREAD

**Issue by Resteklicken** [THM-ATLAS/vue-frontend#282]
We need a system to track a users login state so we don't fire off endless API requests for unauthenticated users etc.   
Since backend support for unauthorized requests is neither available nor planned, client side management of some sort of login token will be necessary.

**Comment by hwgn** [comment]
It seems that we will be getting a request similar to `/loggedin`, which will work unauthorized and will return a boolean if we are logged in or not (aka if a cookie is supplied and if it is valid). Would you say this be enough or is there something else we'd need?
