### ISSUE TITLE
[Minor] Read login api call results and redirect to `.data.redirect` value 

### ISSUE THREAD

**Issue by hwgn** [THM-ATLAS/vue-frontend#318]
This should make the login page redirect work. Something like

```
LoginService.login(...).then(r => {
  router.push(r.data.redirect);
  });
```

should probably do the trick

**Comment by ninahammer2** [comment]
Wollte dazu nochmal einwerfen: 

axios gibt euch nicht die 302 response zurück (die den Location Header hat), sondern die 200 response, die ihr danach bekommt. (Also wir geben euch 302 -> / zurück, / wird automatisch angefragt, es kommt ein 200 zurück). Also müsst ihr nicht diesen Header auslesen, sondern für jeden response 200 schauen, ob die url, von der die kommt, auch die ist, die ursprünglich angefragt wurde. Wenn nein: es gab nen Redirect und ihr gebt die url der response an den Router
