### ISSUE TITLE
[Bug] Fix Submissions

### ISSUE THREAD

**Issue by eznavy** [THM-ATLAS/vue-frontend#361]
![image](https://user-images.githubusercontent.com/103522073/177052916-3d8cea3f-8bba-40e3-9040-89c69496f959.png)
^ This has to do with the variable submissionType.

![image](https://user-images.githubusercontent.com/103522073/177053366-dfb6b85a-d5a8-4a19-8b89-46080ed14f1c.png)
^ Submissions aren't displayed anymore.

**Comment by hwgn** [comment]
Is this still an issue? @shinymew2

**Comment by eznavy** [comment]
> Is this still an issue? @shinymew2 

no, I fixed this

**Comment by hwgn** [comment]
Awesome :)
