### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by AnasAhakki** [THM-ATLAS/vue-frontend#5]
make skip to content link visible for...

- [x] desktop
~~mobile~~

**Comment by hwgn** [comment]
Ist Skip-To-Content für mobile überhaupt sinnvoll? Da navigiert man ja effektiv nie via Tabulator, also würde man auch nie den Bedarf haben, zum Content zu springen... 
glaube, da genügt es bis Desktop

**Comment by eznavy** [comment]
das hab ich mir auch gedacht, aber es kann ja durchaus jemand am PC im schmalen Fenster arbeiten wollen, und dann wäre das unschön... :D ich weiß auch nicht...

**Comment by hwgn** [comment]
Ah, das stimmt natürlich. Solange der link dann irgendwie sichtbar ist sollte das ja genügen
