### ISSUE TITLE
[Minor] Save settings using api

### ISSUE THREAD

**Issue by hwgn** [THM-ATLAS/vue-frontend#75]

**Comment by hwgn** [comment]
Should be doable now, the docs have a `PUT /settings` and `GET /settings/(id)`

**Comment by hwgn** [comment]
@Resteklicken are you still doing this?

**Comment by Resteklicken** [comment]
@hwgn yessir

**Comment by Resteklicken** [comment]
It's all there in theory, but I can't finish this until proper management of login state in implemented.

**Comment by hwgn** [comment]
What do you mean by that? Would we need to use something like VueX after all?
