### ISSUE TITLE
Add a simple landing page

### ISSUE THREAD

**Issue by eznavy** [THM-ATLAS/vue-frontend#9]
The landing page should include the ATLAS logo and a short welcoming text, as well as a search bar to search for courses.

**Comment by hwgn** [comment]
![image](https://user-images.githubusercontent.com/19843204/167452442-e695dd87-3415-42ce-83a4-6af292411ef1.png)
Looks Nice! Dark mode could use some love :D

**Comment by eznavy** [comment]
Totally forgot about that, thanks for the reminder :D
